name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
    
permissions:
  contents: write # used by the softprops/action-gh-release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ Checkout source code
        uses: actions/checkout@v4

      - name: 🔧 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          check-latest: true

      - name: 📦 Build
        run: go build -o thop -v .

      - name: 📦 Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: thop
          generate_release_notes: true
